version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-service-db
      - POSTGRES_DB=stats-service-db
      - POSTGRES_USER=stats-service-root
      - POSTGRES_PASSWORD=stats-service-root
    volumes:
      - ./logs:/stats-server-logs

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-service-db
      - POSTGRES_USER=stats-service-root
      - POSTGRES_PASSWORD=stats-service-root

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
